difficulty = "EASY"
tags = ["AICC", "Math", "BA1"]

[question]

title = "Complexité polynomiale"
text = """
        \\text{Vrai ou Faux: \\\\
        \\sum_{k=0}^{n} a_k \\cdot n^d \\text{ is } \\Theta(n^{d+1})
       """

[answer]

processors = ["clean-string", "true-false"]
correct = ["True"]

[answer.evaluator]
name = "exact-answer"

