difficulty = "HARD"
tags = ["Calculus", "Math", "BA1"]

[question]

title = "Limite logarithmique"
text = """
        \\text{Calculer} \\\\
        \\lim_{n \\to \\infty} \\sum_{k=2}^{n} \\frac{1}{\\log_k{\\sqrt{n}}} \\\\
        \\text{A: 0} \\\\
        \\text{B: 1} \\\\
        \\text{C: 2} \\\\
        \\text{D: 3} \\\\
       """

[answer]

processors = ["clean-string", "true-false"]
correct = ["C"]

[answer.evaluator]
name = "mcq"

