# This is a TOML test file

title = "TOML Example"

[programming]
    status = "i love programming"

    [programming.cpp]
    iq = 150
    comment = "have a job"

    [programming.java]
    iq = 90
    comment = "why i am still here"

    [programming.html]
    iq = -1
    comment = "did you actually say \"programming\""

    [programming.python]
    iq = 110
    comment = "where do i put parenthesis ?"
